CREATE TABLE ACCESS_LOG 
(
"ACCESSLOGID" INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
USERACCOUNTID INTEGER, 
"DATE" VARCHAR(20), 
"TIME" VARCHAR(20)
);
