CREATE TABLE CUSTOMER 
(
CUSTOMERID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1  
NOT NULL GENERATED ALWAYS AS IDENTITY, 
"NAME" VARCHAR(50), 
CONTACTNUMBER INTEGER, 
EMAIL VARCHAR(50), 
BILLINGADDRESS VARCHAR(100), 
ISREGISTERED BOOLEAN, 
PRIMARY KEY (CUSTOMERID)
);
