CREATE TABLE "CUSTOMER"
(
"CUSTOMERID" INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
"NAME" VARCHAR(50), 
DATEOFBIRTH VARCHAR(10), 
GENDER VARCHAR(20),
CONTACTNUMBER VARCHAR(12), 
EMAIL VARCHAR(50), 
BILLINGADDRESS VARCHAR(100),
PASSWORD VARCHAR(120), 
PROMOTIONALNEWSLETTER BOOLEAN, 
REWARDPOINTS INTEGER,  
ISREGISTERED BOOLEAN
);
