CREATE TABLE "CUSTOMER"
(
"CUSTOMERID" INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
"NAME" VARCHAR(50), 
CONTACTNUMBER VARCHAR(12), 
EMAIL VARCHAR(50), 
BILLINGADDRESS VARCHAR(100), 
ISREGISTERED BOOLEAN
);

