CREATE TABLE STAFF 
(
STAFFID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1  
NOT NULL GENERATED ALWAYS AS IDENTITY, 
"NAME" VARCHAR(50), EMAIL VARCHAR(50), 
PHONENUMBER INTEGER, 
ADDRESS VARCHAR(100), 
STAFFTYPE VARCHAR(20), 
ACTIONHISTORY VARCHAR(100), 
USERACCOUNTID INTEGER, 
PRIMARY KEY (STAFFID)
);
