CREATE TABLE USER_ACCOUNT 
(
USERACCOUNTID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1  
NOT NULL GENERATED ALWAYS AS IDENTITY, 
USERNAME VARCHAR(20), 
PASSWORD VARCHAR(120), 
DATEOFBIRTH VARCHAR(10), 
GENDER VARCHAR(20), 
PROMOTIONALNEWSLETTER BOOLEAN, 
REWARDPOINTS INTEGER, 
PRIMARY KEY (USERACCOUNTID)
);
