/* Create table for User_Account */

CREATE TABLE USER_ACCOUNT 
(
"USERACCOUNTID" INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
USERNAME VARCHAR(100), 
PASSWORD VARCHAR(120), 
DATEOFBIRTH VARCHAR(10), 
GENDER VARCHAR(20), 
PROMOTIONALNEWSLETTER BOOLEAN, 
REWARDPOINTS INTEGER
);

/*Create table for Access Log */

CREATE TABLE ACCESS_LOG 
(
"ACCESSLOGID" INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
USERACCOUNTID INTEGER, 
"DATE" VARCHAR(20), 
"TIME" VARCHAR(20),
"ACTION" VARCHAR(20)
);

/* Create table for Customer */

CREATE TABLE "CUSTOMER"
(
"CUSTOMERID" INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
"NAME" VARCHAR(50), 
CONTACTNUMBER VARCHAR(12), 
EMAIL VARCHAR(50), 
BILLINGADDRESS VARCHAR(100), 
ISREGISTERED BOOLEAN
);

/* Create table for Customer_User */

CREATE TABLE CUSTOMER_USER 
(
USERACCOUNTID INTEGER NOT NULL,
CUSTOMERID INTEGER NOT NULL,
PRIMARY KEY(CUSTOMERID, USERACCOUNTID)

);

/* Create table for Staff */

CREATE TABLE STAFF 
(
"STAFFID" INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
"NAME" VARCHAR(50), EMAIL VARCHAR(50), 
PHONENUMBER VARCHAR(12), 
ADDRESS VARCHAR(100), 
STAFFTYPE VARCHAR(20), 
ACTIONHISTORY VARCHAR(100), 
USERACCOUNTID INTEGER,
FOREIGN KEY (USERACCOUNTID) REFERENCES USER_ACCOUNT
);

